[31m[NOVO_NORDISK][39m [31m90437[39m 2024-09-19 10-09:10 +07:00 [31m  ERROR[39m [33m[I18nService][39m [31mTranslation "validate.FIELD.PHONE" in "en" does not exist.[39m - {"stack":[null]}
[31m[NOVO_NORDISK][39m [31m90437[39m 2024-09-19 10-09:20 +07:00 [31m  ERROR[39m [33m[I18nService][39m [31mTranslation "validate.FIELD.PHONE" in "en" does not exist.[39m - {"stack":[null]}
[31m[NOVO_NORDISK][39m [31m90437[39m 2024-09-19 10-09:02 +07:00 [31m  ERROR[39m [33m[I18nService][39m [31mTranslation "validate.FIELD.PHONE" in "en" does not exist.[39m - {"stack":[null]}
[31m[NOVO_NORDISK][39m [31m90437[39m 2024-09-19 10-09:07 +07:00 [31m  ERROR[39m [33m[I18nService][39m [31mTranslation "validate.FIELD.PHONE" in "en" does not exist.[39m - {"stack":[null]}
[31m[NOVO_NORDISK][39m [31m90437[39m 2024-09-19 10-09:55 +07:00 [31m  ERROR[39m [33m[I18nService][39m [31mTranslation "validate.FIELD.PHONE" in "en" does not exist.[39m - {"stack":[null]}
[31m[NOVO_NORDISK][39m [31m90437[39m 2024-09-19 10-09:02 +07:00 [31m  ERROR[39m [33m[QUERY_FAILED][39m [31mðŸ”¥ TypeORM query error. Message: Error: Failed to cancel request in 5000ms.[39m - {"stack":["QueryFailedError: Error: Failed to cancel request in 5000ms\n    at <anonymous> (/Users/mac/Documents/GitHub/be-novo/node_modules/typeorm/driver/src/driver/sqlserver/SqlServerQueryRunner.ts:282:30)\n    at /Users/mac/Documents/GitHub/be-novo/node_modules/mssql/lib/base/request.js:440:25\n    at Request.userCallback (/Users/mac/Documents/GitHub/be-novo/node_modules/mssql/lib/tedious/request.js:492:15)\n    at Request.Request.callback (/Users/mac/Documents/GitHub/be-novo/node_modules/tedious/src/request.ts:379:14)\n    at apply (/Users/mac/Documents/GitHub/be-novo/node_modules/tedious/src/connection.ts:3772:20)\n    at dispatchEvent (/Users/mac/Documents/GitHub/be-novo/node_modules/tedious/src/connection.ts:2313:15)\n    at cancelTimeout (/Users/mac/Documents/GitHub/be-novo/node_modules/tedious/src/connection.ts:2209:10)\n    at Timeout._onTimeout (/Users/mac/Documents/GitHub/be-novo/node_modules/tedious/src/connection.ts:2156:14)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)"]}
[31m[NOVO_NORDISK][39m [31m90437[39m 2024-09-19 10-09:37 +07:00 [31m  ERROR[39m [33m[I18nService][39m [31mTranslation "validate.FIELD.USER_ID" in "en" does not exist.[39m - {"stack":[null]}
[31m[NOVO_NORDISK][39m [31m90437[39m 2024-09-19 10-09:49 +07:00 [31m  ERROR[39m [33m[I18nService][39m [31mTranslation "validate.FIELD.USER_ID" in "en" does not exist.[39m - {"stack":[null]}
[31m[NOVO_NORDISK][39m [31m90437[39m 2024-09-19 10-09:49 +07:00 [31m  ERROR[39m [33m[I18nService][39m [31mTranslation "validate.FIELD.USER_ID" in "en" does not exist.[39m - {"stack":[null]}
[31m[NOVO_NORDISK][39m [31m98283[39m 2024-09-19 10-09:27 +07:00 [31m  ERROR[39m [33m[I18nService][39m [31mTranslation "validate.FIELD.USER_ID" in "en" does not exist.[39m - {"stack":[null]}
[31m[NOVO_NORDISK][39m [31m98283[39m 2024-09-19 10-09:28 +07:00 [31m  ERROR[39m [33m[I18nService][39m [31mTranslation "validate.FIELD.USER_ID" in "en" does not exist.[39m - {"stack":[null]}
